### ISSUE TITLE
coffee script plugin

### ISSUE THREAD

**Issue by guybedford** [jspm/plugins#3]

**Comment by forresto** [comment]
What would it take to make this happen? For CS in npm, we already have

```
 "browserify": {
  "transform": [
    "coffeeify"
  ]
},
```

in package.json.

**Comment by guybedford** [comment]
See the jsx plugin as an example at https://github.com/floatdrop/plugin-jsx.

**Comment by guybedford** [comment]
Note also this repo is deprecated, plugins repos are listed in the registry here - https://github.com/jspm/registry/blob/master/registry.json#L2.

**Comment by forresto** [comment]
Thanks. This the first search result for `jspm coffeescript`.
